"""Emit LaTeX tables for the AdaGuard TDSC paper.

Reads JSONs from data/paper_data/ and writes .tex snippets to
paper_artifacts/tables/. Each snippet is a standalone tabular
meant to be \\input{} from the Overleaf source — no preamble,
no \\begin{table} wrapper (so the author can choose placement
and caption).

Usage:
  python scripts/paper/build_tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from paper._data import (  # noqa: E402
    REPO_ROOT, DEFENCE_LABELS, DEFENCE_ORDER,
    ATTACK_LABELS, ATTACK_ORDER,
    load_defence_sweep, load_defence_sweep_multiseed, aggregate_multiseed,
    load_v13_random_sweep, aggregate_v13,
    load_consistency, load_client_diversity,
    defence_matrix, best_defence_per_attack,
)

OUT_DIR = REPO_ROOT / "paper_artifacts" / "tables"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def _fmt(v, spec="{:.2f}"):
    if v is None:
        return "--"
    try:
        return spec.format(float(v))
    except (TypeError, ValueError):
        return str(v)


def _bold_if(cell: str, cond: bool) -> str:
    return "\\textbf{" + cell + "}" if cond else cell


# --------------------------------------------------------------------------
# Table III: defence x attack matrix at B=1 (PSNR / LPIPS / ASR)
# --------------------------------------------------------------------------

def build_table_defence_matrix(sweep) -> str:
    grid = defence_matrix(sweep, batch=1)
    # Prefer breaching-backed GradInv if present, else fall back to Geiping recipe.
    use_breaching = any(
        (d, "gradinversion_breaching", 1) in sweep for d in DEFENCE_ORDER
    )
    attacks_ordered = ["gradinversion_breaching" if use_breaching else "gradinversion",
                       "ggcdm", "gi_nas"]

    # Best defence (lowest PSNR) per attack, excluding 'none'.
    grid_for_best = {a: {d: sweep.get((d, a, 1), {}) for d in DEFENCE_ORDER
                         if (d, a, 1) in sweep}
                     for a in attacks_ordered}
    best = best_defence_per_attack(grid_for_best, "psnr", lower_is_better=True)

    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        "% Defence x attack matrix at B=1 (iDLG regime).",
        "% Columns: V1 None | V2 FHE | V4 MaskCrypt | V6 AdaGuard-Fisher",
        "\\begin{tabular}{l l S[table-format=2.2] S[table-format=1.3] S[table-format=1.3]}",
        "\\toprule",
        "Attack & Defence & {PSNR (dB)} & {LPIPS} & {Label ASR} \\\\",
        "\\midrule",
    ]

    for attack in attacks_ordered:
        attack_label = ATTACK_LABELS.get(attack, attack)
        for i, defence in enumerate(DEFENCE_ORDER):
            key = (defence, attack, 1)
            if key not in sweep:
                continue
            m = sweep[key]
            psnr = m.get("psnr")
            lpips = m.get("lpips")
            asr = (m.get("label_recovery") or {}).get("asr")
            is_best = (defence == best.get(attack))
            # Bold the best (lowest PSNR) non-trivial cell.
            psnr_str = _fmt(psnr, "{:.2f}")
            lpips_str = _fmt(lpips, "{:.3f}")
            asr_str = _fmt(asr, "{:.3f}")
            if is_best:
                psnr_str = "\\bfseries " + psnr_str
            row_attack = attack_label if i == 0 else ""
            lines.append(
                f"{row_attack} & {DEFENCE_LABELS[defence]} & "
                f"{psnr_str} & {lpips_str} & {asr_str} \\\\"
            )
        lines.append("\\midrule")

    # Trim trailing midrule.
    if lines[-1] == "\\midrule":
        lines[-1] = "\\bottomrule"
    else:
        lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


def build_table_defence_matrix_multiseed(multiseed_sweep) -> str:
    """Multi-seed variant: emits ``mean $\\pm$ std`` cells with seed count.

    Prefers ``gradinversion_breaching`` for the GradInv row when any seed
    has it; else falls back to the Geiping-recipe ``gradinversion`` key.
    Cells with a single seed render as the bare value (no ``$\\pm$``).
    """
    summary = aggregate_multiseed(multiseed_sweep)

    # Choose GradInv variant: prefer breaching if any seed has it.
    use_breaching = any(
        (d, "gradinversion_breaching", 1) in multiseed_sweep
        for d in DEFENCE_ORDER
    )
    attacks_ordered = [
        "gradinversion_breaching" if use_breaching else "gradinversion",
        "ggcdm", "gi_nas",
    ]

    # Best defence per attack = lowest mean PSNR across seeds, excluding "none".
    best = {}
    for a in attacks_ordered:
        candidates = {}
        for d in DEFENCE_ORDER:
            if d == "none":
                continue
            cell = summary.get((d, a, 1))
            if not cell:
                continue
            mu = (cell.get("psnr") or {}).get("mean")
            if mu is None:
                continue
            candidates[d] = mu
        if candidates:
            best[a] = min(candidates, key=candidates.get)

    # Inspect total seed coverage so the caption note is accurate.
    seeds_seen = set()
    for by_seed in multiseed_sweep.values():
        seeds_seen.update(by_seed.keys())
    n_seeds = len(seeds_seen)

    def _ms(cell, key, spec):
        info = (cell or {}).get(key) or {}
        mu = info.get("mean")
        sd = info.get("std")
        n = info.get("n", 0)
        if mu is None:
            return "--"
        if n <= 1:
            return spec.format(mu)
        return f"{spec.format(mu)} $\\pm$ {spec.format(sd)}"

    seed_list = ", ".join(f"seed {s}" for s in sorted(seeds_seen, key=lambda x: int(x)))
    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        f"% Defence x attack matrix at B=1, multi-seed ({n_seeds} seeds: {seed_list}).",
        "% Cells are mean $\\pm$ std across seeds; single-seed cells omit std.",
        "% Columns: V1 None | V2 FHE | V4 MaskCrypt | V6 AdaGuard-Fisher",
        "\\begin{tabular}{l l c c c}",
        "\\toprule",
        "Attack & Defence & PSNR (dB) & LPIPS & Label ASR \\\\",
        "\\midrule",
    ]
    for attack in attacks_ordered:
        attack_label = ATTACK_LABELS.get(attack, attack)
        # Build all rows for this attack (skip if no data at all).
        attack_rows = []
        for i, defence in enumerate(DEFENCE_ORDER):
            cell = summary.get((defence, attack, 1))
            if not cell:
                continue
            psnr_str = _ms(cell, "psnr", "{:.2f}")
            lpips_str = _ms(cell, "lpips", "{:.3f}")
            asr_str = _ms(cell, "asr", "{:.3f}")
            if defence == best.get(attack) and psnr_str != "--":
                psnr_str = "\\textbf{" + psnr_str + "}"
            row_attack = attack_label if not attack_rows else ""
            attack_rows.append(
                f"{row_attack} & {DEFENCE_LABELS[defence]} & "
                f"{psnr_str} & {lpips_str} & {asr_str} \\\\"
            )
        if attack_rows:
            lines.extend(attack_rows)
            lines.append("\\midrule")

    # Trim trailing midrule.
    if lines[-1] == "\\midrule":
        lines[-1] = "\\bottomrule"
    else:
        lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Table IV: attack hyperparameters
# --------------------------------------------------------------------------

def build_table_attack_hparams() -> str:
    rows = [
        ("GradInversion (Yin 2021)",
         "Geiping 2020 recipe (ours; see \\S\\ref{sec:repro-note})",
         "20\\,000", "Adam lr=0.1, cosine decay",
         "TV $10^{-4}$, cosine-distance loss"),
        ("GGCDM (Meng 2025)",
         "DPS proxy (ours, ref impl unavailable)",
         "100", "DPS guidance $t{:}1000{\\to}0$",
         "guidance rate 0.20, scale 1.0, unconditional CIFAR DDPM prior"),
        ("GI-NAS (Yu 2025)",
         "DIP + 5-candidate NAS (ours, ref impl unavailable)",
         "2\\,000", "Adam lr $10^{-3}$, cosine decay",
         "base\\_ch $\\in\\{64,96,128\\}$, skip $\\in\\{\\text{T},\\text{F}\\}$"),
    ]
    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        "\\begin{tabular}{l l r l l}",
        "\\toprule",
        "Attack & Implementation & Iters. & Optimizer & Regularizers / Hyperparameters \\\\",
        "\\midrule",
    ]
    for name, impl, it, opt, reg in rows:
        lines.append(f"{name} & {impl} & {it} & {opt} & {reg} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Table V: non-IID client diversity histogram
# --------------------------------------------------------------------------

def build_table_client_diversity(rows) -> str:
    if not rows:
        return "% (No client diversity data — rerun with --list-clients.)\n"
    from collections import Counter
    counter = Counter(r["n_unique"] for r in rows)
    n_total = len(rows)
    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        "% Distribution of unique labels per client batch (B=16 saved).",
        "\\begin{tabular}{r r r}",
        "\\toprule",
        "Unique labels per client & \\# clients & \\% of round \\\\",
        "\\midrule",
    ]
    for k in sorted(counter):
        pct = 100.0 * counter[k] / n_total
        lines.append(f"{k} & {counter[k]} & {pct:.1f}\\% \\\\")
    lines += [
        "\\midrule",
        f"Total & {n_total} & 100.0\\% \\\\",
        "\\bottomrule",
        "\\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Table VI: artifact self-consistency
# --------------------------------------------------------------------------

def build_table_consistency(cons) -> str:
    if not cons:
        return "% (No consistency report found.)\n"
    worst = cons.get("worst_layers") or []
    max_rd = cons.get("max_rel_diff")
    # Compute verdict from data, do not trust a stale field in the JSON.
    try:
        m = float(max_rd)
        if m <= 1e-3:
            verdict = "strict pass ($\\leq 10^{-3}$)"
        elif m <= 1e-2:
            verdict = "within GPU non-determinism ($\\leq 10^{-2}$)"
        else:
            verdict = "FAIL: exceeds GPU non-determinism threshold"
    except (TypeError, ValueError):
        verdict = cons.get("verdict", "--")
    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        "\\begin{tabular}{l l}",
        "\\toprule",
        "Metric & Value \\\\",
        "\\midrule",
        f"Max. layer-wise relative diff. & {_fmt(max_rd, '{:.2e}')} \\\\",
        f"Mean layer-wise relative diff. & {_fmt(cons.get('mean_rel_diff'), '{:.2e}')} \\\\",
        f"Number of layers checked & {cons.get('n_layers', '--')} \\\\",
        "\\midrule",
        f"Threshold (strict) & $\\leq 10^{{-3}}$ \\\\",
        f"Threshold (within GPU non-determinism) & $\\leq 10^{{-2}}$ \\\\",
        f"Verdict & {verdict} \\\\",
    ]
    if worst:
        lines.append("\\midrule")
        lines.append("\\multicolumn{2}{l}{\\textbf{Worst-case layers (top 3)}} \\\\")
        for w in worst[:3]:
            name = str(w.get("name", "--")).replace("_", "\\_")
            rel = _fmt(w.get("rel_diff"), "{:.2e}")
            lines.append(f"\\quad {name} & {rel} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Table VII: Fisher-vs-random ablation at fixed rho=10% (V4 vs V13).
# --------------------------------------------------------------------------

def build_table_fisher_vs_random(multiseed, v13_sweep) -> str:
    """Emit V4 (Fisher) vs V13 (random) comparison at fixed rho=10%.

    For each attack: three rows — V4 mean +/- std, V13 mean +/- std, and the
    Delta = (random - Fisher). Higher Delta PSNR means Fisher beats random
    (random reconstruction is closer to original); lower Delta LPIPS in the
    same direction.
    """
    fisher_summary = aggregate_multiseed(multiseed)
    random_summary = aggregate_v13(v13_sweep)

    use_breaching = ("fisher", "gradinversion_breaching", 1) in multiseed
    grad_key = "gradinversion_breaching" if use_breaching else "gradinversion"
    attacks_ordered = [grad_key, "ggcdm", "gi_nas"]

    seeds_seen = set()
    for by_seed in v13_sweep.values():
        seeds_seen.update(by_seed.keys())
    n_seeds = len(seeds_seen)

    def _ms(cell, key, spec):
        info = (cell or {}).get(key) or {}
        mu = info.get("mean")
        sd = info.get("std")
        n = info.get("n", 0)
        if mu is None:
            return "--"
        if n <= 1:
            return spec.format(mu)
        return f"{spec.format(mu)} $\\pm$ {spec.format(sd)}"

    def _delta(fisher_cell, random_cell, key, spec):
        fmu = ((fisher_cell or {}).get(key) or {}).get("mean")
        rmu = ((random_cell or {}).get(key) or {}).get("mean")
        if fmu is None or rmu is None:
            return "--"
        d = rmu - fmu
        sign = "+" if d > 0 else ""
        return sign + spec.format(d)

    seed_list = ", ".join(f"seed {s}" for s in sorted(seeds_seen, key=lambda x: int(x)))
    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        f"% Fisher-vs-random ablation at fixed rho=10%, B=1, multi-seed (n={n_seeds}: {seed_list}).",
        "% V4: Fisher-targeted SHE; V13: uniform-random mask of the same K.",
        "% Higher Delta PSNR = Fisher beats random (random is closer to original).",
        "\\begin{tabular}{l l c c c}",
        "\\toprule",
        "Attack & Configuration & PSNR (dB) & LPIPS & Label ASR \\\\",
        "\\midrule",
    ]

    for attack in attacks_ordered:
        attack_label = ATTACK_LABELS.get(attack, attack)
        fisher_cell = fisher_summary.get(("fisher", attack, 1))
        v13_attack = "gradinversion" if attack == "gradinversion_breaching" else attack
        random_cell = random_summary.get((v13_attack, 1))
        if fisher_cell is None or random_cell is None:
            continue

        psnr_f = _ms(fisher_cell, "psnr", "{:.2f}")
        psnr_r = _ms(random_cell, "psnr", "{:.2f}")
        psnr_d = _delta(fisher_cell, random_cell, "psnr", "{:.2f}")
        lpips_f = _ms(fisher_cell, "lpips", "{:.3f}")
        lpips_r = _ms(random_cell, "lpips", "{:.3f}")
        lpips_d = _delta(fisher_cell, random_cell, "lpips", "{:.3f}")
        asr_f = _ms(fisher_cell, "asr", "{:.3f}")
        asr_r = _ms(random_cell, "asr", "{:.3f}")

        lines.append(
            f"{attack_label} & V4 (Fisher, $\\rho{{=}}10\\%$) & "
            f"{psnr_f} & {lpips_f} & {asr_f} \\\\"
        )
        lines.append(
            f"             & V13 (random, $\\rho{{=}}10\\%$) & "
            f"{psnr_r} & {lpips_r} & {asr_r} \\\\"
        )
        lines.append(
            f"             & $\\Delta$ (random $-$ Fisher) & "
            f"{psnr_d} & {lpips_d} & -- \\\\"
        )
        lines.append("\\midrule")

    if lines[-1] == "\\midrule":
        lines[-1] = "\\bottomrule"
    else:
        lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


def main():
    sweep = load_defence_sweep()
    multiseed = load_defence_sweep_multiseed()
    cons = load_consistency()
    diversity = load_client_diversity()
    v13 = load_v13_random_sweep()

    # Count seeds per cell to decide whether to emit a multi-seed table.
    seeds_seen = set()
    for by_seed in multiseed.values():
        seeds_seen.update(by_seed.keys())

    outputs = {
        "table_defence_matrix.tex": build_table_defence_matrix(sweep),
        "table_attack_hparams.tex": build_table_attack_hparams(),
        "table_client_diversity.tex": build_table_client_diversity(diversity),
        "table_consistency.tex": build_table_consistency(cons),
    }
    if len(seeds_seen) >= 2:
        outputs["table_defence_matrix_multiseed.tex"] = (
            build_table_defence_matrix_multiseed(multiseed)
        )
    else:
        # Skip emitting the multi-seed table until at least one extra seed
        # lands locally; print a hint so the operator knows it was a no-op.
        print(f"  (multi-seed table skipped: only {len(seeds_seen)} seed(s) "
              f"present — drop more sweeps under data/paper_data/defence/seedNNN/)")

    if v13:
        outputs["table_fisher_vs_random.tex"] = (
            build_table_fisher_vs_random(multiseed, v13)
        )
    else:
        print("  (Fisher-vs-random table skipped: no V13 JSONs at "
              "data/paper_data/defence/v13_random/)")

    for fname, text in outputs.items():
        path = OUT_DIR / fname
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}  ({len(text)} chars)")


if __name__ == "__main__":
    main()
