"""Emit LaTeX tables for the AdaGuard TDSC paper.

Reads JSONs from data/paper_data/ and writes .tex snippets to
paper_artifacts/tables/. Each snippet is a standalone tabular
meant to be \\input{} from the Overleaf source — no preamble,
no \\begin{table} wrapper (so the author can choose placement
and caption).

Usage:
  python scripts/paper/build_tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from paper._data import (  # noqa: E402
    REPO_ROOT, DEFENCE_LABELS, DEFENCE_ORDER,
    ATTACK_LABELS, ATTACK_ORDER,
    load_defence_sweep, load_consistency, load_client_diversity,
    defence_matrix, best_defence_per_attack,
)

OUT_DIR = REPO_ROOT / "paper_artifacts" / "tables"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def _fmt(v, spec="{:.2f}"):
    if v is None:
        return "--"
    try:
        return spec.format(float(v))
    except (TypeError, ValueError):
        return str(v)


def _bold_if(cell: str, cond: bool) -> str:
    return "\\textbf{" + cell + "}" if cond else cell


# --------------------------------------------------------------------------
# Table III: defence x attack matrix at B=1 (PSNR / LPIPS / ASR)
# --------------------------------------------------------------------------

def build_table_defence_matrix(sweep) -> str:
    grid = defence_matrix(sweep, batch=1)
    # Prefer breaching-backed GradInv if present, else fall back to Geiping recipe.
    use_breaching = any(
        (d, "gradinversion_breaching", 1) in sweep for d in DEFENCE_ORDER
    )
    attacks_ordered = ["gradinversion_breaching" if use_breaching else "gradinversion",
                       "ggcdm", "gi_nas"]

    # Best defence (lowest PSNR) per attack, excluding 'none'.
    grid_for_best = {a: {d: sweep.get((d, a, 1), {}) for d in DEFENCE_ORDER
                         if (d, a, 1) in sweep}
                     for a in attacks_ordered}
    best = best_defence_per_attack(grid_for_best, "psnr", lower_is_better=True)

    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        "% Defence x attack matrix at B=1 (iDLG regime).",
        "% Columns: V1 None | V2 FHE | V4 MaskCrypt | V6 AdaGuard-Fisher",
        "\\begin{tabular}{l l S[table-format=2.2] S[table-format=1.3] S[table-format=1.3]}",
        "\\toprule",
        "Attack & Defence & {PSNR (dB)} & {LPIPS} & {Label ASR} \\\\",
        "\\midrule",
    ]

    for attack in attacks_ordered:
        attack_label = ATTACK_LABELS.get(attack, attack)
        for i, defence in enumerate(DEFENCE_ORDER):
            key = (defence, attack, 1)
            if key not in sweep:
                continue
            m = sweep[key]
            psnr = m.get("psnr")
            lpips = m.get("lpips")
            asr = (m.get("label_recovery") or {}).get("asr")
            is_best = (defence == best.get(attack))
            # Bold the best (lowest PSNR) non-trivial cell.
            psnr_str = _fmt(psnr, "{:.2f}")
            lpips_str = _fmt(lpips, "{:.3f}")
            asr_str = _fmt(asr, "{:.3f}")
            if is_best:
                psnr_str = "\\bfseries " + psnr_str
            row_attack = attack_label if i == 0 else ""
            lines.append(
                f"{row_attack} & {DEFENCE_LABELS[defence]} & "
                f"{psnr_str} & {lpips_str} & {asr_str} \\\\"
            )
        lines.append("\\midrule")

    # Trim trailing midrule.
    if lines[-1] == "\\midrule":
        lines[-1] = "\\bottomrule"
    else:
        lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Table IV: attack hyperparameters
# --------------------------------------------------------------------------

def build_table_attack_hparams() -> str:
    rows = [
        ("GradInversion (Yin 2021)",
         "\\texttt{breaching.seethroughgradients}",
         "20\\,000", "Adam lr=0.1, cosine decay",
         "TV $10^{-4}$, DeepInversion BN-match $0.1$, Langevin $\\sigma{=}0.01$"),
        ("GGCDM (Meng 2025)",
         "DPS proxy (ours, ref impl unavailable)",
         "100", "DPS guidance $t{:}1000{\\to}0$",
         "guidance rate 0.20, scale 1.0, unconditional CIFAR DDPM prior"),
        ("GI-NAS (Yu 2025)",
         "DIP + 5-candidate NAS (ours, ref impl unavailable)",
         "2\\,000", "Adam lr $10^{-3}$, cosine decay",
         "base\\_ch $\\in\\{64,96,128\\}$, skip $\\in\\{\\text{T},\\text{F}\\}$"),
    ]
    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        "\\begin{tabular}{l l r l l}",
        "\\toprule",
        "Attack & Implementation & Iters. & Optimizer & Regularizers / Hyperparameters \\\\",
        "\\midrule",
    ]
    for name, impl, it, opt, reg in rows:
        lines.append(f"{name} & {impl} & {it} & {opt} & {reg} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Table V: non-IID client diversity histogram
# --------------------------------------------------------------------------

def build_table_client_diversity(rows) -> str:
    if not rows:
        return "% (No client diversity data — rerun with --list-clients.)\n"
    from collections import Counter
    counter = Counter(r["n_unique"] for r in rows)
    n_total = len(rows)
    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        "% Distribution of unique labels per client batch (B=16 saved).",
        "\\begin{tabular}{r r r}",
        "\\toprule",
        "Unique labels per client & \\# clients & \\% of round \\\\",
        "\\midrule",
    ]
    for k in sorted(counter):
        pct = 100.0 * counter[k] / n_total
        lines.append(f"{k} & {counter[k]} & {pct:.1f}\\% \\\\")
    lines += [
        "\\midrule",
        f"Total & {n_total} & 100.0\\% \\\\",
        "\\bottomrule",
        "\\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Table VI: artifact self-consistency
# --------------------------------------------------------------------------

def build_table_consistency(cons) -> str:
    if not cons:
        return "% (No consistency report found.)\n"
    worst = cons.get("worst_layers") or []
    max_rd = cons.get("max_rel_diff")
    # Compute verdict from data, do not trust a stale field in the JSON.
    try:
        m = float(max_rd)
        if m <= 1e-3:
            verdict = "strict pass ($\\leq 10^{-3}$)"
        elif m <= 1e-2:
            verdict = "within GPU non-determinism ($\\leq 10^{-2}$)"
        else:
            verdict = "FAIL: exceeds GPU non-determinism threshold"
    except (TypeError, ValueError):
        verdict = cons.get("verdict", "--")
    lines = [
        "% Auto-generated by scripts/paper/build_tables.py",
        "\\begin{tabular}{l l}",
        "\\toprule",
        "Metric & Value \\\\",
        "\\midrule",
        f"Max. layer-wise relative diff. & {_fmt(max_rd, '{:.2e}')} \\\\",
        f"Mean layer-wise relative diff. & {_fmt(cons.get('mean_rel_diff'), '{:.2e}')} \\\\",
        f"Number of layers checked & {cons.get('n_layers', '--')} \\\\",
        "\\midrule",
        f"Threshold (strict) & $\\leq 10^{{-3}}$ \\\\",
        f"Threshold (within GPU non-determinism) & $\\leq 10^{{-2}}$ \\\\",
        f"Verdict & {verdict} \\\\",
    ]
    if worst:
        lines.append("\\midrule")
        lines.append("\\multicolumn{2}{l}{\\textbf{Worst-case layers (top 3)}} \\\\")
        for w in worst[:3]:
            name = str(w.get("name", "--")).replace("_", "\\_")
            rel = _fmt(w.get("rel_diff"), "{:.2e}")
            lines.append(f"\\quad {name} & {rel} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main():
    sweep = load_defence_sweep()
    cons = load_consistency()
    diversity = load_client_diversity()

    outputs = {
        "table_defence_matrix.tex": build_table_defence_matrix(sweep),
        "table_attack_hparams.tex": build_table_attack_hparams(),
        "table_client_diversity.tex": build_table_client_diversity(diversity),
        "table_consistency.tex": build_table_consistency(cons),
    }

    for fname, text in outputs.items():
        path = OUT_DIR / fname
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}  ({len(text)} chars)")


if __name__ == "__main__":
    main()
